sonar.projectKey=devops-backend
sonar.projectName=DevOps Backend
sonar.projectVersion=1.0

sonar.sources=.
sonar.inclusions=.

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.git/**,**/coverage/**

sonar.sourceEncoding=UTF-8
